# Generated by Django 4.2.5 on 2023-10-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_Cart_App', '0002_alter_product_table_options'),
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_item',
            new_name='cart_item_table',
        ),
        migrations.RenameModel(
            old_name='cart',
            new_name='cart_table',
        ),
        migrations.AlterModelTable(
            name='cart_item_table',
            table='cart_item_table',
        ),
        migrations.AlterModelTable(
            name='cart_table',
            table='cart_table',
        ),
    ]
