# Generated by Django 4.2.5 on 2023-10-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_Cart_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_table',
            options={'ordering': ('p_name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
